AWSTemplateFormatVersion: 2010-09-09
Description: mindLAMP Platform v2 DocumentDB setup

Parameters:
  ProjectName:
    Description: Project name that will be used as the prefix for all deployed resources
    Type: String
    ConstraintDescription: Project name that will be used as the prefix for all deployed resources
    Default: 'mindLAMP-platform-v2'

  KMSKeyArn:
    Description: The key ARN for the KMS key used to encrypt the DocDB cluster at rest
    Type: AWS::SSM::Parameter::Value<String>
    Default: /mindLAMP-platform-v2/kms/key_arn

  VPC:
    Description: The id for the VPC into which the DocDB cluster should be deployed
    Type: AWS::SSM::Parameter::Value<String>
    Default: /mindLAMP-platform-v2/vpc/id
    
  PrivateSubnet1:
    Description: The id for one of the two private subnets in the VPC where the DocDB cluster should be deployed
    Type: AWS::SSM::Parameter::Value<String>
    Default: /mindLAMP-platform-v2/vpc/private_subnet_1
    
  PrivateSubnet2:
    Description: The id for one of the two private subnets in the VPC where the DocDB cluster should be deployed
    Type: AWS::SSM::Parameter::Value<String>
    Default: /mindLAMP-platform-v2/vpc/private_subnet_2

  DBAdminUsername:
    NoEcho: "true"
    Description : "The database admin user name"
    Type: "String"
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription : "Must begin with a letter and contain only alphanumeric characters."
    Default: "docdbadmin"

  DBAdminUserPassword:
    NoEcho: "true"
    Description : "The database admin user password"
    Type: "String"
    MinLength: "1"
    MaxLength: "41"
    AllowedPattern : "[a-zA-Z0-9]+"
    ConstraintDescription : "must contain only alphanumeric characters."
    Default: "iamdocdbadmin"

  DBInstanceClass:
    Description : "Instance class. Please refer to: https://docs.aws.amazon.com/documentdb/latest/developerguide/db-instance-classes.html#db-instance-classes-by-region"
    Type: "String"
    AllowedValues:
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.12xlarge
      - db.r5.24xlarge                             
    ConstraintDescription : "Instance type must be of the ones supported for the region. Please refer to: https://docs.aws.amazon.com/documentdb/latest/developerguide/db-instance-classes.html#db-instance-classes-by-region"
    Default: "db.t3.medium"

Resources:
  DBCluster:
    Type: AWS::DocDB::DBCluster
    Properties: 
      BackupRetentionPeriod: 8
      DBClusterIdentifier: !Sub ${ProjectName}-docdb-cluster
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      DBSubnetGroupName: !Ref DBSubnetGrouop
      DeletionProtection: false
      EngineVersion: 4.0.0
      KmsKeyId: !Ref KMSKeyArn
      MasterUsername:
        Fn::Sub: "{{resolve:secretsmanager:${DBClusterSecret}::username}}"
      MasterUserPassword:
        Fn::Sub: "{{resolve:secretsmanager:${DBClusterSecret}::password}}"
      Port: 27017
      PreferredBackupWindow: 07:34-08:04
      PreferredMaintenanceWindow: sat:04:51-sat:05:21
      SnapshotIdentifier: !Sub ${ProjectName}-docdb-cluster-snapshot-id
      StorageEncrypted: true
      Tags:
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-cluster
      VpcSecurityGroupIds: 
        - String

  DBClusterParameterGroup:
    Type: AWS::DocDB::DBClusterParameterGroup
    Properties: 
      Description: !Sub Parameter group for ${ProjectName}-docdb-cluster 
      Family: docdb3.6
      Name: !Sub ${ProjectName}-docdb-cluster-parameter-group
      Parameters:
            audit_logs: disabled
            tls: enabled
            ttl_monitor: enabled
      Tags:
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-cluster-parameter-group
  
  DBSubnetGroup: 
    Type: "AWS::DocDB::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: Subnet group for ${ProjectName}-docdb-cluster
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags: 
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-subnet-group

  DBInstance:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBClusterIdentifier: !Ref DBCluster
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Sub ${ProjectName}-docdb-instance
      PreferredMaintenanceWindow: sat:06:54-sat:07:24
      Tags: 
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-instance
    DependsOn: DBCluster

  DBClusterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: ${ProjectName}-docdb-cluster secret
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
      Tags:
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-cluster-secret

  SecretDocDB:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: "/s360/demoSISDB/credentials"
      Description: "Secrets to provide access to s360-sisdb-mysql RDS instance"
      SecretString: '{"username":"admin","password":"master123"}'
  
  SecretRDSInstanceAttachment:
    Type: "AWS::SecretsManager::SecretTargetAttachment"
    Properties:
      SecretId: !Ref MyRDSSecret
      TargetId: !Ref rdssisdemodb
      TargetType: AWS::RDS::DBInstance

Outputs:
  ClusterId:
    Value: !Ref DBCluster
  ClusterEndpoint:
    Value: !GetAtt DBCluster.Endpoint
  ClusterPort:
    Value: !GetAtt DBCluster.Port
  EngineVersion:
    Value: "4.0.0"

