AWSTemplateFormatVersion: 2010-09-09
Description: mindLAMP Platform v2 DocumentDB setup
Transform: AWS::SecretsManager-2020-07-23

Parameters:
  ProjectName:
    ConstraintDescription: Project name that will be used as the prefix for all deployed resources
    Default: mindLAMP-platform-v2
    Description: Project name that will be used as the prefix for all deployed resources
    Type: String

  KmsKeyArn:
    Default: /mindLAMP-platform-v2/kms/key_arn
    Description: The key ARN for the KMS key used to encrypt all project resources at rest
    Type: AWS::SSM::Parameter::Value<String>

  PrivateSubnet1:
    Default: /mindLAMP-platform-v2/vpc/private_subnet_1
    Description: The id for Private Subnet 1 in the VPC where the DocDB cluster should be deployed
    Type: AWS::SSM::Parameter::Value<String>

  PrivateSubnet2:
    Default: /mindLAMP-platform-v2/vpc/private_subnet_2
    Description: The id for Private Subnet 2 in the VPC where the DocDB cluster should be deployed
    Type: AWS::SSM::Parameter::Value<String>

  PrivateSubnet3:
    Default: /mindLAMP-platform-v2/vpc/private_subnet_3
    Description: The id for Private Subnet 3 in the VPC where the DocDB cluster should be deployed
    Type: AWS::SSM::Parameter::Value<String>

  VPC:
    Default: /mindLAMP-platform-v2/vpc/id
    Description: The id for the VPC into which the DocDB cluster should be deployed
    Type: AWS::SSM::Parameter::Value<String>

  DocDBInstanceClass:
    AllowedValues:
      - db.t3.medium
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.12xlarge
      - db.r5.24xlarge                             
    ConstraintDescription : DocDB instance class options.
    Default: db.r5.large
    Description : DocDB instance class options.
    Type: String

Resources:
  DocDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub ${ProjectName} DocDB security group
      GroupName: !Sub ${ProjectName}-docdb-sg
      Tags:
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-sg
      VpcId: !Ref VPC

  DocDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties: 
      BackupRetentionPeriod: 8
      DBClusterIdentifier: !Sub ${ProjectName}-docdb-cluster
      DBClusterParameterGroupName: !Ref DocDBClusterParameterGroup
      DBSubnetGroupName: !Ref DocDBSubnetGroup
      DeletionProtection: false
      EngineVersion: 4.0.0
      KmsKeyId: !Ref KmsKeyArn
      MasterUsername:
        Fn::Sub: '{{resolve:secretsmanager:${DocDBClusterSecret}::username}}'
      MasterUserPassword:
        Fn::Sub: '{{resolve:secretsmanager:${DocDBClusterSecret}::password}}'
      Port: 27017
      PreferredBackupWindow: 07:34-08:04
      PreferredMaintenanceWindow: sat:04:51-sat:05:21
      StorageEncrypted: true
      Tags:
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-cluster
      VpcSecurityGroupIds: 
        - !Ref DocDBSecurityGroup

  DocDBClusterParameterGroup:
    Type: AWS::DocDB::DBClusterParameterGroup
    Properties: 
      Description: !Sub Parameter group for ${ProjectName}-docdb-cluster 
      Family: docdb4.0
      Name: !Sub ${ProjectName}-docdb-cluster-parameter-group
      Parameters:
            audit_logs: disabled
            tls: enabled
            ttl_monitor: enabled
      Tags:
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-cluster-parameter-group

  DocDBInstance:
    Type: AWS::DocDB::DBInstance
    DependsOn: DocDBCluster
    Properties:
      DBClusterIdentifier: !Ref DocDBCluster
      DBInstanceClass: !Ref DocDBInstanceClass
      DBInstanceIdentifier: !Sub ${ProjectName}-docdb-instance
      PreferredMaintenanceWindow: sat:06:54-sat:07:24
      Tags: 
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-instance

  DocDBSubnetGroup: 
    Type: AWS::DocDB::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Subnet group for ${ProjectName}-docdb-cluster
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        - !Ref PrivateSubnet3
      Tags: 
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-subnet-group

  ParamDocDBClusterEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Description: DocDB cluster endpoint
      Name: /mindLAMP-platform-v2/docdb/docdb_cluster_endpoint
      Tags:
        Project: !Sub ${ProjectName}
      Type: String
      Value: !GetAtt DocDBCluster.Endpoint

  ParamDocDBClusterId:
    Type: AWS::SSM::Parameter
    Properties:
      Description: DocDB cluster id
      Name: /mindLAMP-platform-v2/docdb/docdb_cluster_id
      Tags:
        Project: !Sub ${ProjectName}
      Type: String
      Value: !Ref DocDBCluster

  ParamDocDBClusterPort:
    Type: AWS::SSM::Parameter
    Properties:
      Description: DocDB cluster port
      Name: /mindLAMP-platform-v2/docdb/docdb_cluster_port
      Tags:
        Project: !Sub ${ProjectName}
      Type: String
      Value: !GetAtt DocDBCluster.Port

  ParamDocDBSecurityGroup:
    Type: AWS::SSM::Parameter
    Properties:
      Description: DocDB security group id
      Name: /mindLAMP-platform-v2/docdb/docdb_security_group
      Tags:
        Project: !Sub ${ProjectName}
      Type: String
      Value: !Ref DocDBSecurityGroup

  SecretsManagerVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: true
      SecurityGroupIds: 
        - !Ref DocDBSecurityGroup
      ServiceName:
        Fn::Sub: com.amazonaws.${AWS::Region}.secretsmanager
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        - !Ref PrivateSubnet3
      VpcEndpointType: Interface
      VpcId: !Ref VPC

  DocDBClusterSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: ${ProjectName}-docdb-cluster secret
      GenerateSecretString:
        ExcludeCharacters: "\"@/\\"
        GenerateStringKey: password
        PasswordLength: 16
        SecretStringTemplate: '{"username": "docdbadmin","ssl": true}'
      Tags:
        - Key: Project
          Value: !Sub ${ProjectName}
        - Key: Name
          Value: !Sub ${ProjectName}-docdb-cluster-secret

  DocDBClusterSecretTargetAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties:
      SecretId: !Ref DocDBClusterSecret
      TargetId: !Ref DocDBCluster
      TargetType: AWS::DocDB::DBCluster

  DocDBClusterSecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    DependsOn: DocDBClusterSecretTargetAttachment
    Properties:
      SecretId: !Ref DocDBClusterSecret
      HostedRotationLambda:
        RotationType: MongoDBSingleUser
        RotationLambdaName: MongoDBSingleUser
        VpcSecurityGroupIds: !Ref DocDBSecurityGroup
        VpcSubnetIds:
          Fn::Join:
          - ","
          - - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
            - !Ref PrivateSubnet3
      RotationRules:
        AutomaticallyAfterDays: 30

Outputs:
  DocDBClusterEndpoint:
    Description: DocDB cluster endpoint
    Value: !GetAtt DocDBCluster.Endpoint

  DocDBClusterId:
    Description: DocDB cluster id
    Value: !Ref DocDBCluster

  DocDBClusterPort:
    Description: DocDB cluster port
    Value: !GetAtt DocDBCluster.Port

  DocDBSecurityGroupId:
    Description: DocDB security group
    Value: !Ref DocDBSecurityGroup
