AWSTemplateFormatVersion: 2010-09-09
Description: mindLAMP Platform v2 KMS key setup

Parameters:
  ProjectName:
    ConstraintDescription: Project name that will be used as the prefix for all deployed resources
    Default: mindLAMP-platform-v2
    Description: Project name that will be used as the prefix for all deployed resources
    Type: String

  KeyAliasNameSuffix:
    ConstraintDescription: Suffix for the CMK key alias name, e.g., GUID; full name is ${ProjectName}-key-${KeyAliasNameSuffix}
    Description: Suffix for the CMK key alias name, e.g., GUID; full name is ${ProjectName}-key-${KeyAliasNameSuffix}
    Type: String

Resources:
  #########################
  #
  # KMS Key
  #
  #########################
  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Symmetric CMK for encrypting all project resources at rest
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: kms-key-policy
        Statement:
        - Sid: Enable IAM User Permissions
          Action: kms:*
          Effect: Allow
          Principal:
            AWS: !Join
              - ''
              - - 'arn:aws:iam::'
                - !Ref AWS::AccountId
                - :root
          Resource: '*'
        - Sid: Allow administration of the key
          Action:
            - kms:Create*
            - kms:Describe*
            - kms:Enable*
            - kms:List*
            - kms:Put*
            - kms:Update*
            - kms:Revoke*
            - kms:Disable*
            - kms:Get*
            - kms:Delete*
            - kms:ScheduleKeyDeletion
            - kms:CancelKeyDeletion
          Effect: Allow
          Principal:
            AWS: !Join
              - ''
              - - 'arn:aws:iam::'
                - !Ref AWS::AccountId
                - :role/Admin
          Resource: '*'
        - Sid: Allow use of the key
          Action:
            - kms:DescribeKey
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey
            - kms:GenerateDataKeyWithoutPlaintext
          Effect: Allow
          Principal:
            AWS: !Join
              - ''
              - - 'arn:aws:iam::'
                - !Ref AWS::AccountId
                - :role/Admin
          Resource: '*'
      PendingWindowInDays: 7
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-key-${KeyAliasNameSuffix}

  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${ProjectName}-${KeyAliasNameSuffix}
      TargetKeyId: !Ref KmsKey

  #########################
  #
  # Parameter Store Parameters
  #
  #########################
  ParamKeyArn:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The ARN for KmsKey
      Name: /mindLAMP-platform-v2/kms/key_arn
      Type: String
      Value: !Ref KmsKey

  ParamKeyAlias:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The alias for KmsKey
      Name: /mindLAMP-platform-v2/kms/key_alias
      Type: String
      Value: !Ref KmsKeyAlias

Outputs:
  KeyArn:
    Description: The ARN for KmsKey
    Value: !Ref KmsKey

  KeyAlias:
    Description: The Alias for KmsKey
    Value: !Ref KmsKeyAlias
